### ISSUE TITLE
soscks4 proxy refused

### ISSUE THREAD

**Issue by rerterggg** [romis2012/aiosocksy#1]
```
import asyncio
import aiohttp
from aiosocksy import Socks5Auth
from aiosocksy.connector import ProxyConnector, ProxyClientRequest


async def fetch(url):
    connector = ProxyConnector()
    socks = 'socks4://127.0.0.1:8080'
    async with aiohttp.ClientSession(connector=connector, request_class=ProxyClientRequest) as session:
        async with session.get(url, proxy=socks) as response:
            print(await response.text())


loop = asyncio.get_event_loop()
loop.run_until_complete(fetch('http://ie.com/'))
```

generates:
Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "<stdin>", line 5, in fetch
  File "/home/debian/.local/lib/python3.6/site-packages/aiohttp/client.py", line 783, in __aenter__
    self._resp = await self._coro
  File "/home/debian/.local/lib/python3.6/site-packages/aiohttp/client.py", line 320, in _request
    traces=traces
  File "/home/debian/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 418, in connect
    traces=traces
  File "/home/debian/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 728, in _create_connection
    traces=traces
  File "/home/debian/.local/lib/python3.6/site-packages/aiosocksy/connector.py", line 56, in _create_proxy_connection
    return await self._create_socks_connection(req, traces=traces)
  File "/home/debian/.local/lib/python3.6/site-packages/aiosocksy/connector.py", line 108, in _create_socks_connection
    server_hostname=req.host if sslcontext else None)
  File "/home/debian/.local/lib/python3.6/site-packages/aiosocksy/connector.py", line 60, in _wrap_create_socks_connection
    return await create_connection(*args, **kwargs)
  File "/home/debian/.local/lib/python3.6/site-packages/aiosocksy/__init__.py", line 81, in create_connection
    await waiter
aiosocksy.errors.SocksError: Can not connect to ie.com:80. [Errno 0x5b]: Request rejected or failed

socks5 works

**Comment by rerterggg** [comment]
requests.get('http://ie.com/',proxies={'http':socks}) returns 200
